version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend/
    # volumes:
    #   - /home/giovannifoletto/Documents/UNI/SE-BarAdvisor/backend:/app
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
  frontend:
    build: frontend/
    volumes:
      - /home/giovannifoletto/Documents/UNI/SE-BarAdvisor/frontend:/app
    links:
      - backend
    ports:
      - "8080:8080"
