version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: backend/
    volumes:
      - /home/giovannifoletto/Documents/UNI/SE-BarAdvisor/backend:/app
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - PORT=400
      - FRONT_PORT=8080
      - FRONT_HOST=localhost
      - DB_URL_LOCAL=mongodb://mongo/restAPI
      - DB_URL_CLUSTER=mongodb://mongo/restAPI
      - PORT=4000
      - EMAIL_SERVICE=hotmail
      - EMAIL_USERNAME=nodeproject@outlook.com
      - EMAIL_PASSWORD=progettonode2022
      - EMAIL_FROM=nodeproject@outlook.com
  frontend:
    build: front-vue/
    volumes:
      - /home/giovannifoletto/Documents/UNI/SE-BarAdvisor/front-vue:/app
    links:
      - backend
    ports:
      - "8080:8080"
  mongo:
    image: mongo