DELETE http://localhost:4000/api/v1/eventi/62969e4bf054120b95f6ea23/commenti/629f7fde737a4d5f4f77fce8
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTc2ZDg3YzMwZjFiOGFhOWMyZTQwZiIsIm5vbWUiOiJjaWFvIiwiZW1haWwiOiJjaWFvQGdtYWlsLmNvbSIsInJ1b2xvIjoiQ2xpZW50ZSIsImxvY2FsZSI6IiIsImlhdCI6MTY1NDYyMDAxMCwiZXhwIjoxNjU0NzA2NDEwfQ.oDqF7Vzpus7bCh5UWUFyW-rbvNJWpD7U7GDmYRRSHQc'

###

DELETE http://localhost:4000/api/v1/eventi/62969e4bf054120b95f6ea23/commenti/629f7fde737a4d5f4f77fce8
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTc2ZDg3YzMwZjFiOGFhOWMyZTQwZiIsIm5vbWUiOiJjaWFvIiwiZW1haWwiOiJjaWFvQGdtYWlsLmNvbSIsInJ1b2xvIjoiQ2xpZW50ZSIsImxvY2FsZSI6IiIsImlhdCI6MTY1NDYyMDAxMCwiZXhwIjoxNjU0NzA2NDEwfQ.oDqF7Vzpus7bCh5UWUFyW-rbvNJWpD7U7GDmYRRSHQc'

###

GET http://localhost:4000/api/v1/eventi/62969e4bf054120b95f6ea22