name: Testing Backend

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lancio dei test.
        run: | 
          echo ${{ secrets.DB_URL_CLUSTER_TESTING }}
          npm ci
          npm run test:ci
        env:
          NODE_ENV: testing
          DB_URL_CLUSTER_TESTING: ${{ secrets.DB_URL_CLUSTER_TESTING }}