name: Deploy on Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    name: Build and push docker image to the container
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: "Login to heroku:container"
        run: docker login --username=${{ docker.username }} --email=${{ secrets.HEROKU_MAIL}} --password=${{ docker.TOKEN }} registry.heroku.com

# docker tag se-baradvisor registry.heroku.com/se-baradvisor/web
# docker push registry.heroku.com/se-baradvisor/web

# Create a docker file to do all this thing inside that 

# TODO: 
# - loggin
# - CI/CD procedur accomplish
# - set up Jenkins or Chef to automate buildin, testing and deploy on heroku

      - name: "Docker buil image"
        run: docker 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_MAIL }}
          branch: main
        env:
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          PORT: 80
          DB_URL_CLUSTER: ${{ secrets.DB_URL_CLUSTER }},
          SECRET_KEY: ${{ secrets.SECRET_KEY }},
          EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }},
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }},
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }},
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }} 